main/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r"^$", views.HomePageView.as_view(), name='HomePageView'),
	url(r'^school/(?P<sid>[\w\-]+)$', views.SchoolView.as_view(), name='SchoolView'),
	url(r"^add/school/", views.SchoolCreateView.as_view(), name='create_school'),
	url(r"^list/$", views.search_view, name='SchoolListView'),
	url(r"^compare/$", views.CompareSchoolView.as_view(), name='compare'),
	url(r'^search/', include('haystack.urls')),
]

school_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from main.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^', include('main.urls')),
]
urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

import cloudinary
from cloudinary.models import CloudinaryField
# Create your models here.

class UserType(models.Model):
	"""
		UserType: Used to store the type of user Ex: Student, Principal, Professor etc.
	"""
	name = models.CharField("Type of User", max_length=50)

	def __str__(self):
		return self.name

class School(models.Model):
	"""
	School: Strores all details about the school
	"""
	sid = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=30, blank=True, null=True)
	category =  models.ForeignKey('Category', blank=True, null=True)
	address_line1 = models.CharField(max_length=30, blank=True, null=True)
	address_line2 = models.CharField(max_length=30, blank=True, null=True)
	area = models.CharField(max_length=30, blank=True, null=True)
	city = models.CharField(max_length=30, blank=True, null=True)
	state = models.CharField(max_length=30, blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	facilities = models.CharField(max_length=100 ,blank=True, null=True)
	contact_number = models.CharField(max_length=20,blank=True, null=True)
	website = models.CharField(max_length=30, blank=True, null=True)
	photos = CloudinaryField('image',blank=True, null=True)
	admission_info = models.TextField(blank=True, null=True)
	overall_rating = models.FloatField(blank=True, null=True)
	board = models.ForeignKey('Board', blank=True, null=True)
	added_by = models.ForeignKey("User", blank=True, null=True, related_name='school_creator')
	def __str__(self):
		return self.name


class User(AbstractUser):
	user_type = models.ForeignKey("UserType", blank=True, null=True)
	school_admin = models.ForeignKey('School', blank=True, null=True, related_name='school_admin')
	employment_details = models.TextField(blank=True, null=True)
	phone = models.CharField(max_length=20, blank=True, null=True)
	address = models.TextField(blank=True, null=True)
	photo = models.TextField(blank=True, null=True)
	child_school = models.ForeignKey('School', blank=True, null=True, related_name='child_school')
	facility_preferred = models.ManyToManyField('School')


class Board(models.Model):
	"""
	Facilities: Stores individual facility provided info
	"""
	name = models.CharField(max_length=10, blank=True, null=True)

	def __str__(self):
		return self.name


class Reviews(models.Model):
	"""
	Reviews: Stores reviews for each school
	"""
	school = models.ForeignKey('School', blank=True, null=True)
	parent = models.ForeignKey('User', blank=True, null=True)
	review_content = models.TextField(blank=True, null=True)
	rating = models.CharField(max_length=10)

	def __str__(self):
		return parent.name

class Category(models.Model):
	"""
	Category: Stores the type of school, primary, secondary,etc.
	"""
	name = models.CharField(max_length=10, blank=True, null=True)

	def __str__(self):
		return self.name
	

main/forms.py
from django import forms

from .models import *
from django.contrib.auth import get_user_model

class SchoolCreateForm(forms.ModelForm):
	class Meta:
		User = get_user_model()
		model = School
		exclude = ('added_by', 'overall_rating')

class SearchForm(forms.ModelForm):
	class Meta:
		model = School
		exclude = ('added_by','sid','contact_number','website','photos','admission_info',)

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, View, CreateView
from django.views.generic.list import ListView

from django.urls import reverse_lazy

from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseRedirect

from .models import *
from .forms import *
# Create your views here.

class HomePageView(TemplateView):
	template_name = "home.html"

	def get_context_data(self, *args, **kwargs):
		context = super(HomePageView, self).get_context_data(**kwargs)
		board = Board.objects.all()
		types = Category.objects.all()
		context['board_list'] =  board
		context['type_list'] =  types
		return context


class SchoolView(TemplateView):
	template_name = "school.html"

	def get_context_data(self, *args, **kwargs):
		context = super(SchoolView, self).get_context_data(**kwargs)
		school_id = kwargs.get('sid', None)
		school_details = School.objects.get(sid=school_id)
		context['school'] =  school_details
		return context


class SchoolCreateView(CreateView):
	model = School
	template_name = "school_create.html"

	success_url = reverse_lazy("school")
	error_url = reverse_lazy('school_create')
	form_class = SchoolCreateForm

	def get_context_data(self, *args, **kwargs):
		context = super(SchoolCreateView, self).get_context_data(*args, **kwargs)
		return context
	
	def form_valid(self, form):
		create = form.save(commit=False)
		create.added_by = self.request.user
		create.save()
		return HttpResponseRedirect('/list/')
	
	def form_invalid(self,form):
		print(form.errors)
		return HttpResponseRedirect('/add/school')


class SchoolListView(ListView):
	model = School
	template_name = "school_list.html"

	def get_context_data(self, **kwargs):
		print('rating list')
		context = super(SchoolListView, self).get_context_data(**kwargs)
		school_list = School.objects.all()
		rating_list = []
		for school in school_list:
			rating_list.append(school.overall_rating)
		print('-----')
		print(rating_list)
		context['ratings'] = list(set(rating_list))
		return context

def search_view(request):
	context = {}
	schools = School.objects.all()
	form = SearchForm(request.GET)
	if form.is_valid():
		if form.cleaned_data["city"] and form.cleaned_data["name"] and form.cleaned_data["board"] and form.cleaned_data["type"]:
			schools = schools.filter(city__icontains=form.cleaned_data["city"], 
				name__icontains=form.cleaned_data["name"], 
				board__name__icontains=form.cleaned_data["board"],
				category__name__icontains=form.cleaned_data["type"])
		elif form.cleaned_data["city"] and form.cleaned_data["name"] and form.cleaned_data["board"] and not form.cleaned_data["type"]:
			schools = schools.filter(city__icontains=form.cleaned_data["city"], 
				name__icontains=form.cleaned_data["name"], 
				board__name__icontains=form.cleaned_data["board"])
		elif form.cleaned_data["city"] and form.cleaned_data["name"] and not form.cleaned_data["board"] and not form.cleaned_data["type"]:
			schools = schools.filter(city__icontains=form.cleaned_data["city"], 
				name__icontains=form.cleaned_data["name"],)
		else:
			pass
	rating_list = []
	for school in schools:
		rating_list.append(school.overall_rating)
	context['ratings'] = list(set(rating_list))
	context["form"] = form
	context['object_list'] = schools
	context['board'] = Board.objects.all()
	return render(request, "school_list.html",context)


class CompareSchoolView(ListView):
	model = School
	template_name = "compare.html"

	def get_context_data(self, *args, **kwargs):
		context = super(CompareSchoolView, self).get_context_data(**kwargs)
		return context

templates/compare.html
{% load static %}
<!DOCTYPE html>
<html class="no-js"> <!--<![endif]-->
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Bingo One page parallax responsive HTML Template ">
  
  <meta name="author" content="Themefisher.com">

  <title>Add School</title>

<!-- Mobile Specific Meta
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/fontastic.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/tagify.css' %}">
</head>

<body>
	{% include 'partials/nav_primary.html' %}

	<div class="col-md-12 pt-5">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<select class="form-control compare_one">
						<option>Select School</option>
						{% for school in object_list %}
						<option val="{{school.sid}}" image="{{school.photos.url}}" name="{{school.name}}" rating="{{school.overall_rating}}" board="{{school.board.name}}">{{school.name}}</option>
						{% endfor %}
					</select>
					<p class="mt-5 show_one_photo"></p>
					<p class="mt-5 show_one_rating"></p>
					<p class="mt-5 show_one_board"></p>
				</div>
				<div class="col-md-4">
					<select class="form-control compare_two">
						<option>Select School</option>
						{% for school in object_list %}
						<option val="{{school.sid}}" image="{{school.photos.url}}" name="{{school.name}}" rating="{{school.overall_rating}}" board="{{school.board.name}}">{{school.name}}</option>
						{% endfor %}
					</select>
					<p class="mt-5 show_two_photo"></p>
					<p class="mt-5 show_two_rating"></p>
					<p class="mt-5 show_two_board"></p>
				</div>
				<div class="col-md-4">
					<select class="form-control compare_three">
						<option>Select School</option>
						{% for school in object_list %}
						<option val="{{school.sid}}" image="{{school.photos.url}}" name="{{school.name}}" rating="{{school.overall_rating}}" board="{{school.board.name}}">{{school.name}}</option>
						{% endfor %}
					</select>
					<p class="mt-5 show_three_photo"></p>
					<p class="mt-5 show_three_rating"></p>
					<p class="mt-5 show_three_board"></p>
				</div>
			</div>
		</div>
	</div>

	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript">
    	$(function() {
    		$('.compare_one').change(function() {
    			var rating = $('option:selected', this).attr('rating');
    			var board = $('option:selected', this).attr('board');
    			var image = $('option:selected', this).attr('image');
    			$('.show_one_photo').html('<img style="width:200px;height:200px;" src="' + image + '">');
    			$('.show_one_rating').html(rating);
    			$('.show_one_board').html(board);
    		})
    		$('.compare_two').change(function() {
    			var rating = $('option:selected', this).attr('rating');
    			var board = $('option:selected', this).attr('board');
    			var image = $('option:selected', this).attr('image');
    			$('.show_two_photo').html('<img style="width:200px;height:200px;" src="' + image + '">');
    			$('.show_two_rating').html(rating);
    			$('.show_two_board').html(board);
    		})
    		$('.compare_three').change(function() {
    			var rating = $('option:selected', this).attr('rating');
    			var board = $('option:selected', this).attr('board');
    			var image = $('option:selected', this).attr('image');
    			$('.show_three_photo').html('<img style="width:200px;height:200px;" src="' + image + '">');
    			$('.show_three_rating').html(rating);
    			$('.show_three_board').html(board);
    		})
    	})
    </script>
</body>
</html>

templates/partials/footer.html
<footer id="footer" class="bg-one">
  <div class="top-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-3 col-md-3 col-lg-3">
          <h3>INFORMATION</h3>
          <ul>
            <li><a href="#">Payment Option</a></li>
            <li><a href="#">Free Schedule</a></li>
            <li><a href="#">Getting Started</a></li>
            <li><a href="#">Bitcoin Calculator</a></li>
          </ul>
        </div>
        <!-- End of .col-sm-3 -->

        <div class="col-sm-3 col-md-3 col-lg-3">
          <h3>Our Services</h3>
          <ul>
            <li><a href="#">Graphic Design</a></li>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
          </ul>
        </div>
        <!-- End of .col-sm-3 -->

        <div class="col-sm-3 col-md-3 col-lg-3">
          <h3>Quick Links</h3>
          <ul>
            <li><a href="#">Partners</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">FAQ’s</a></li>
            <li><a href="#">Badges</a></li>
          </ul>
        </div>
        <!-- End of .col-sm-3 -->

        <div class="col-sm-3 col-md-3 col-lg-3">
          <h3>Follow Us</h3>
          <ul>
              <li>
                  <a href="">
                      Facebook
                  </a>
              </li>
              <li>
                  <a href="">
                      Twitter
                  </a>
              </li>
              <li>
                  <a href="">
                      Linkedin
                  </a>
              </li>
              <li>
                  <a href="">
                      Google PLus
                  </a>
              </li>
          </ul>
        </div>
        <!-- End of .col-sm-3 -->

      </div>
    </div> <!-- end container -->
  </div>
  <div class="footer-bottom">
    <h5>Copyright 2018. All rights reserved.</h5>
    <h6><a href="">School Aggregator</a></h6>
  </div>
</footer>

templates/partials/nav_primary.html
   <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <a href="index.html" class="navbar-brand">ChalkRoot</a>
            
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <!--div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="/" class="nav-link">Home</a>
              </li>
              <li class="nav-item"><a href="{% url 'create_school' %}" class="nav-link ">Add School</a>
              </li>
              <li class="nav-item"><a href="{% url 'SchoolListView' %}" class="nav-link ">School List</a>
              </li>
              <li class="nav-item"><a href="{% url 'compare' %}" class="nav-link ">Compare</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">About Us</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">Contact Us</a>
              </li>
            </ul>
          </div-->
        </div>
      </nav>
    </header>

templates/school_create.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Bingo One page parallax responsive HTML Template ">

  <title>Add School</title>

<!-- Mobile Specific Meta
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/fontastic.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/tagify.css' %}">
</head>

<body id="body">

 <!--
  Start Preloader
  ==================================== -->
  <div id="preloader">
    <div class="preloader">
      <div class="sk-circle1 sk-child"></div>
      <div class="sk-circle2 sk-child"></div>
      <div class="sk-circle3 sk-child"></div>
      <div class="sk-circle4 sk-child"></div>
      <div class="sk-circle5 sk-child"></div>
      <div class="sk-circle6 sk-child"></div>
      <div class="sk-circle7 sk-child"></div>
      <div class="sk-circle8 sk-child"></div>
      <div class="sk-circle9 sk-child"></div>
      <div class="sk-circle10 sk-child"></div>
      <div class="sk-circle11 sk-child"></div>
      <div class="sk-circle12 sk-child"></div>
    </div>
  </div> 
 {% include 'partials/nav_primary.html' %}
<!-- Srart Contact Us
		=========================================== -->		
	<section class="contact-us section bg-gray" id="contact">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="title text-center">
						<h2>Add School.</h2>
						<span class="border"></span>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!</p>
					</div>
				</div>
			</div>
			<div class="row">
				<!-- Contact Form -->
				<div class="contact-form col-12 col-md-6  mx-auto" >
					<form id="contact-form" method="post" role="form">{% csrf_token %}
					
						<div class="form-group">
							{% render_field form.sid class="form-control" placeholder="School ID" %}
						</div>
						<div class="form-group">
							{% render_field form.name class="form-control" placeholder="School Name" %}
						</div>
						<div class="form-group">
							{% render_field form.address_line1 class="form-control" placeholder="School Address Line 1" %}
						</div>
						<div class="form-group">
							{% render_field form.address_line2 class="form-control" placeholder="School Address Line 2" %}
						</div>
						<div class="form-group">
							{% render_field form.area class="form-control" placeholder="Area" %}
						</div>
						<div class="form-group">
							{% render_field form.city class="form-control" placeholder="City" %}
						</div>
						<div class="form-group">
							{% render_field form.state class="form-control" placeholder="State" %}
						</div>
						<div class="form-group">
							{% render_field form.description class="form-control" placeholder="Description" %}
						</div>
						<div class="form-group">
							<input name='facilities' class='form-control' id="id_facilities" placeholder='Facilities' autofocus>
						</div>
						<div class="form-group">
							{% render_field form.contact_number class="form-control" placeholder="Contact Number" %}
						</div>
						<div class="form-group">
							{% render_field form.website class="form-control" placeholder="Website" %}
						</div>
						<div class="form-group">
							{% render_field form.photos class="form-control" placeholder="Photos" %}
						</div>
						<div class="form-group">
							{% render_field form.admission_info class="form-control" placeholder="Admission Info" %}
						</div>
						<div class="form-group">
							{% render_field form.academic_record class="form-control" placeholder="Academic Record" %}
						</div>
						<div id="mail-success" class="success">
							Thank you. The Mailman is on His Way :)
						</div>
						
						<div id="mail-fail" class="error">
							Sorry, don't know what happened. Try later :(
						</div>
						
						<div id="cf-submit">
							<input type="submit" id="contact-submit" class="btn btn-transparent" value="Submit">
						</div>						
						
					</form>
				</div>
				<!-- ./End Contact Form -->
			</div> <!-- end row -->
			
		</div> <!-- end container -->
	</section> <!-- end section -->

{% include 'partials/footer.html' %}
    
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/tagify.polyfills.js' %}"></script>
    <script src="{% static 'js/tagify.js' %}"></script>
    <script src="{% static 'js/jQuery.tagify.js' %}"></script>

<script data-name="basic">
(function(){

var input = document.querySelector('input[name=facilities]'),
    tagify = new Tagify(input, {
        whitelist : [
        'Playground', 'Canteen', 'Transport',
        ],
        blacklist : [""]
    });

// "remove all tags" button event listener
document.querySelector('.tags--removeAllBtn')
    .addEventListener('click', tagify.removeAllTags.bind(tagify))

// Chainable event listeners
tagify.on('add', onAddTag)
      .on('remove', onRemoveTag)
      .on('invalid', onInvalidTag);

// tag added callback
function onAddTag(e){
    console.log(e, e.detail);
    console.log( tagify.DOM.originalInput.value )
    tagify.off('add', onAddTag) // exmaple of removing a custom Tagify event
}

// tag remvoed callback
function onRemoveTag(e){
    console.log(e, e.detail);
}

// invalid tag added callback
function onInvalidTag(e){
    console.log(e, e.detail);
}

})()
</script>
  </body>
  </html>

templates/search/search.html
<h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.name }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>